"""empty message

Revision ID: 34ba8f480db6
Revises: d06d9d5fff98
Create Date: 2017-06-17 15:22:07.153886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34ba8f480db6'
down_revision = 'd06d9d5fff98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###
